### ISSUE TITLE
py: unable to load object bundle executable when including Max packages

### ISSUE THREAD

**Issue by danagilliann** [grrrr/py#13]
Hello! I am currently trying to use pyext with Max for Live on a Mac. I read the instructions [here](https://github.com/grrrr/py/issues/7#issuecomment-295756452), downloaded `py.package-i386-system-2.7.zip`, unzipped the file, and put them in `~/Documents/Max 8/Packages`. I then opened `thread-1.mxb`, but when I opened it, the following error outputted in the Max console:

![screen shot 2019-01-27 at 10 43 53 pm](https://user-images.githubusercontent.com/9299928/51813627-3fecf780-2285-11e9-9baf-6668aa0f8b8e.png)

I'm new to developing in Max, and I would really appreciate some help :)

**Comment by grrrr** [comment]
Hi, the py/pyext binary has not been built for 64 bit architectures which Max 8 require. This is signified by the `-i386-` name tag and is connected to the fact the 64 bit support of [flext](https://github.com/grrrr/flext) under Max is still experimental (and buggy).

**Comment by danagilliann** [comment]
Thank you for the speedy response! Ah I didn't realize that. So there's absolutely no way to get pyext running on 64 bit architectures?

**Comment by grrrr** [comment]
There definitely is a way if someone fixes the flext code and builds a py/pyext binary.
