### ISSUE TITLE
Is there a way to call music21 (python3 package) within pyext(currently python2)

### ISSUE THREAD

**Issue by theslyprofessor** [grrrr/py#14]
Hello,
The main impetus I have for using this external is to interface with MIT's excellent toolkit for computer-assisted musicology, "music21," which parses musicxml music notation files, midi, does musical analyses, and many other things. Unfortunately, music21 has not been compatible with python2 for a couple of years now. I was wondering if there was a way to still make calls to the music21 package without explicitly using Python3, as I know that pyext is a python2 external.

Thanks,
Nakul

**Comment by grrrr** [comment]
Hi Nakul, that py/pyext is a python2 external is not a general restriction. Issue #11 describes some efforts to make the conversion. I am happy about contributions (pull requests) for this.
