### ISSUE TITLE
works on ARM / RaspberryPI / CHIP?

### ISSUE THREAD

**Issue by batchku** [grrrr/py#6]
Hello @grrrr !
Have you or anyone you know tried this external on ARM / RPi?

Ali

**Comment by grrrr** [comment]
Hi Ali,
i haven't tried but i see no principal reason why it shouldn't work.
best, Thomas

--
Thomas Grill
http://grrrr.org

**Comment by batchku** [comment]
Hi Thomas,
Thanks for the quick response.
I'd like to try it; are there binary builds for arm7 anywhere?
Ali

**Comment by umlaeute** [comment]
maybe this might help:

~~~
apt-get install pd-py
~~~

**Comment by grrrr** [comment]
hmmm @umlaeute, 'apt-cache search pd-py' doesn't yield anything for me, still under wheezy. Is it present in jessie or stretch?

**Comment by umlaeute** [comment]
https://packages.debian.org/search?keywords=pd-py lists
- stretch (stable)
- buster (current testing)
- sid (unstable)
