### ISSUE TITLE
installation osx - init folder

### ISSUE THREAD

**Issue by quintendewilde** [grrrr/py#7]
I need to copy py-objectmappings.txt to init folder, which init folder are you talking about. Really interested to get python working on max

**Comment by grrrr** [comment]
Max 6 had an "init" folder in it's application structure (on MacOS /Applications/Max/Cycling '74/init) where objectmappings files could be dropped. Obviously, the structure has changed with Max7, for the new packages format. It would be necessary to bring py/pyext in that folder format and then drop it to /Documents/Max/Packages. I am open for pull requests or other contributions concerning the proper approach.

**Comment by quintendewilde** [comment]
I've tried to create that structure py/pyext/py-objectmappings.txt, rebooted max. Put the directory in the list. But the objects are still unusable. No real answer on fixing the init on max 7, with my google fu

**Comment by quintendewilde** [comment]
Did you managed to get this to work in max7?

**Comment by BLCKPSTV** [comment]
I eventually even installed MAX 6 and did the copied given instruction. But the object still doesn't work.

**Comment by quintendewilde** [comment]
Also what I completely oversaw is that there is no py.mxo in the repository?!

**Comment by grrrr** [comment]
> Also what I completely oversaw is that there is no py.mxo in the repository?!
> 

py.mxo is a binary file whereas github is a source code repository.
For binary files, please visit http://grrrr.org/py, section Download.

**Comment by quintendewilde** [comment]
I've imported the mxo files from you download section, file py.mxo-UB-local-2.6.zip. 
But still no object recognised. Changed from 32bit to 64bit. Also nothing.

**Comment by Dazzid** [comment]
Same issue here, py is recognised on 32 bits but It doesn't find pyext

**Comment by grrrr** [comment]
Hi all, i can confirm that it works, in Max 32-bit mode. The binaries have not been compiled for 64-bit mode yet.
I have created Max packages (named py-package-*.zip) that should be unzipped and dropped into the ~/Documents/Max 7/Packages folder. 
I assume that everyone has Python 2.7 installed these days.
If you use the Python version coming with your OS, you should use the *-system-* variant. If you have Python installed yourself (Python 2.7 installer from python.org), then use the *-local-* variant.
To be honest, i can't test the *-system-* variant, let me know if there are problems with it.
There is some rudimentary help coming with the package. It's user-contributed content and seems to be broken for the signal example. I don't recommend using python for dsp processing anyway.
